import{i as l,S as y,a as f}from"./assets/vendor-f67ecabd.js";(function(){const a=document.createElement("link").relList;if(a&&a.supports&&a.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))i(e);new MutationObserver(e=>{for(const r of e)if(r.type==="childList")for(const n of r.addedNodes)n.tagName==="LINK"&&n.rel==="modulepreload"&&i(n)}).observe(document,{childList:!0,subtree:!0});function s(e){const r={};return e.integrity&&(r.integrity=e.integrity),e.referrerpolicy&&(r.referrerPolicy=e.referrerpolicy),e.crossorigin==="use-credentials"?r.credentials="include":e.crossorigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function i(e){if(e.ep)return;e.ep=!0;const r=s(e);fetch(e.href,r)}})();const t={searchForm:document.querySelector(".search-form"),gallery:document.querySelector(".gallery"),btnLoadMore:document.querySelector(".load-more")};t.btnLoadMore.classList.add("is-hidden");t.searchForm.addEventListener("submit",L);t.btnLoadMore.addEventListener("click",$);let d="",b,c=1;const u=40;async function L(o){if(o.preventDefault(),t.btnLoadMore.classList.add("is-hidden"),d=o.currentTarget.searchQuery.value.trim(),d===""){l.info({message:"Please write something...",position:"topRight",color:"rgba(57, 58, 58, 0.959);"});return}t.gallery.innerHTML="",t.searchForm.reset(),c=1;try{const{hits:s,totalHits:i}=await m(d,c,u);if(i===0){l.error({message:"Sorry, there are no images matching your search query.Please try again.",position:"topRight"}),t.searchForm.reset(),t.btnLoadMore.classList.add("is-hidden"),t.gallery.innerHTML="";return}t.gallery.innerHTML="",i>u&&t.btnLoadMore.classList.remove("is-hidden"),t.gallery.innerHTML="",g(s),b=new y(".gallery a").refresh(),l.success({message:`Hooray! We found ${i} images !!!`,position:"topRight",color:"hsl(26, 83%, 56%)"})}catch(s){console.log(s)}}f.defaults.baseURL="https://pixabay.com/api/";const M="38012427-abdef302c1869514a7af9c6c2";async function m(o,a,s){const{data:i}=await f.get(`?key=${M}&q=${o}&image_type=photo&orientation=horizontal&safesearch=true&page=${a}&per_page=${s}`);return i}function g(o){let a=o.map(({webformatURL:s,largeImageURL:i,tags:e,likes:r,views:n,comments:h,downloads:p})=>`<li class="gallery-item list">
        <a href="${i}">
          <img class="img-item" src="${s}" alt="${e}" width=600px />
        </a>
        <div class="info">
          <p class="info-item"><b class="accent">likes:</b>${r}</p>
          <p class="info-item"><b class="accent">views:</b>${n}</p>
          <p class="info-item"><b class="accent">comments:</b>${h}</p>
          <p class="info-item"><b class="accent">downloads:</b>${p}</p>
        </div>
      </li>`).join("");t.gallery.insertAdjacentHTML("beforeend",a)}async function $(){c+=1;try{const{hits:o,totalHits:a}=await m(d,c,u);g(o);const s=Math.ceil(a/u);c===s&&(l.info({message:"We're sorry, but you've reached the end of search results.",position:"bottomCenter",color:"rgba(57, 58, 58, 0.959);"}),t.btnLoadMore.classList.add("is-hidden"))}catch(o){console.log(o)}}
//# sourceMappingURL=commonHelpers.js.map
