import{S as b,i as c,a as f}from"./assets/vendor-f67ecabd.js";(function(){const i=document.createElement("link").relList;if(i&&i.supports&&i.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))a(e);new MutationObserver(e=>{for(const r of e)if(r.type==="childList")for(const n of r.addedNodes)n.tagName==="LINK"&&n.rel==="modulepreload"&&a(n)}).observe(document,{childList:!0,subtree:!0});function s(e){const r={};return e.integrity&&(r.integrity=e.integrity),e.referrerpolicy&&(r.referrerPolicy=e.referrerpolicy),e.crossorigin==="use-credentials"?r.credentials="include":e.crossorigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function a(e){if(e.ep)return;e.ep=!0;const r=s(e);fetch(e.href,r)}})();const t={searchForm:document.querySelector(".search-form"),gallery:document.querySelector(".gallery"),btnLoadMore:document.querySelector(".load-more")};t.btnLoadMore.classList.add("is-hidden");t.searchForm.addEventListener("submit",L);t.btnLoadMore.addEventListener("click",v);let u="",m=new b(".gallery a"),l=1;const d=40;async function L(o){if(o.preventDefault(),t.btnLoadMore.classList.add("is-hidden"),u=o.currentTarget.searchQuery.value.trim(),u===""){c.info({message:"Please write something...",position:"topRight",color:"rgba(57, 58, 58, 0.959);"});return}t.gallery.innerHTML="",t.searchForm.reset(),l=1;try{const{hits:s,totalHits:a}=await h(u,l,d);if(a===0){c.error({message:"Sorry, there are no images matching your search query.Please try again.",position:"topRight"}),t.searchForm.reset(),t.btnLoadMore.classList.add("is-hidden"),t.gallery.innerHTML="";return}t.gallery.innerHTML="",a<d&&c.info({message:"We're sorry, but you've reached the end of search results.",position:"bottomCenter",color:"rgba(57, 58, 58, 0.959);"}),a>d&&t.btnLoadMore.classList.remove("is-hidden"),t.gallery.innerHTML="",g(s),m.refresh(),c.success({message:`Hooray! We found ${a} images !!!`,position:"topRight",color:"hsl(26, 83%, 56%)"})}catch(s){console.log(s)}}f.defaults.baseURL="https://pixabay.com/api/";const M="38012427-abdef302c1869514a7af9c6c2";async function h(o,i,s){const{data:a}=await f.get(`?key=${M}&q=${o}&image_type=photo&orientation=horizontal&safesearch=true&page=${i}&per_page=${s}`);return a}function g(o){let i=o.map(({webformatURL:s,largeImageURL:a,tags:e,likes:r,views:n,comments:p,downloads:y})=>`<li class="gallery-item list">
        <a href="${a}">
          <img class="img-item" src="${s}" alt="${e}" width=600px />
        </a>
        <div class="info">
          <p class="info-item"><b class="accent">likes:</b>${r}</p>
          <p class="info-item"><b class="accent">views:</b>${n}</p>
          <p class="info-item"><b class="accent">comments:</b>${p}</p>
          <p class="info-item"><b class="accent">downloads:</b>${y}</p>
        </div>
      </li>`).join("");t.gallery.insertAdjacentHTML("beforeend",i)}async function v(){l+=1;try{const{hits:o,totalHits:i}=await h(u,l,d);g(o),m.refresh();const s=Math.ceil(i/d);l===s&&(c.info({message:"We're sorry, but you've reached the end of search results.",position:"bottomCenter",color:"rgba(57, 58, 58, 0.959);"}),t.btnLoadMore.classList.add("is-hidden"))}catch(o){console.log(o)}}
//# sourceMappingURL=commonHelpers.js.map
